/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BasicUserResponse {
  id: string;
  image?: string;
  name?: string;
  username: string;
}
