/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateOrUpdateRemasterPlaysParams = {
  id: string;
  userId?: string;
};
