/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponse } from "./userResponse";

export interface PageResponseUserResponse {
  items: UserResponse[];
  next?: string;
}
