/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RemasterResponse } from "./remasterResponse";

export interface PageResponseRemasterResponse {
  items: RemasterResponse[];
  next?: string;
}
