/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateRemasterRequest {
  description?: string;
  duration: number;
  id: string;
  key: number;
  loops: string;
  mode: number;
  name: string;
  tempo: number;
  timeSignature: number;
  tuning: number;
  url: string;
}
