/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponseRole } from "./userResponseRole";

export interface UserResponse {
  bio?: string;
  email: string;
  id: string;
  image?: string;
  name?: string;
  role: UserResponseRole;
  username: string;
  verified: boolean;
}
