/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  InfiniteData,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  AuthenticationResponse,
  FollowUserParams,
  GetUserByUsernameParams,
  GetUserFollowersParams,
  GetUserFollowingParams,
  PageResponseBasicUserResponse,
  PageResponseUserResponse,
  SearchUsersParams,
  UnfollowUserParams,
  UpdateUserBody,
  UserResponse,
} from "../../model";
import { customInstance } from "../../lib/axios";
import type { BodyType } from "../../lib/axios";

export const updateUser = (updateUserBody: BodyType<UpdateUserBody>) => {
  const formData = new FormData();
  formData.append("request", JSON.stringify(updateUserBody.request));
  if (updateUserBody.imageFile !== undefined) {
    formData.append("imageFile", updateUserBody.imageFile);
  }

  return customInstance<AuthenticationResponse>({
    url: `/user`,
    method: "PUT",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
  });
};

export const getUpdateUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { data: BodyType<UpdateUserBody> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { data: BodyType<UpdateUserBody> },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUser>>,
    { data: BodyType<UpdateUserBody> }
  > = (props) => {
    const { data } = props ?? {};

    return updateUser(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>;
export type UpdateUserMutationBody = BodyType<UpdateUserBody>;
export type UpdateUserMutationError = unknown;

export const useUpdateUser = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { data: BodyType<UpdateUserBody> },
    TContext
  >;
}) => {
  const mutationOptions = getUpdateUserMutationOptions(options);

  return useMutation(mutationOptions);
};
export const unfollowUser = (params: UnfollowUserParams) => {
  return customInstance<string>({
    url: `/user/unfollow`,
    method: "POST",
    params,
  });
};

export const getUnfollowUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unfollowUser>>,
    TError,
    { params: UnfollowUserParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unfollowUser>>,
  TError,
  { params: UnfollowUserParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unfollowUser>>,
    { params: UnfollowUserParams }
  > = (props) => {
    const { params } = props ?? {};

    return unfollowUser(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnfollowUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof unfollowUser>>
>;

export type UnfollowUserMutationError = unknown;

export const useUnfollowUser = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unfollowUser>>,
    TError,
    { params: UnfollowUserParams },
    TContext
  >;
}) => {
  const mutationOptions = getUnfollowUserMutationOptions(options);

  return useMutation(mutationOptions);
};
export const followUser = (params: FollowUserParams) => {
  return customInstance<string>({
    url: `/user/follow`,
    method: "POST",
    params,
  });
};

export const getFollowUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof followUser>>,
    TError,
    { params: FollowUserParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof followUser>>,
  TError,
  { params: FollowUserParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof followUser>>,
    { params: FollowUserParams }
  > = (props) => {
    const { params } = props ?? {};

    return followUser(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type FollowUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof followUser>>
>;

export type FollowUserMutationError = unknown;

export const useFollowUser = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof followUser>>,
    TError,
    { params: FollowUserParams },
    TContext
  >;
}) => {
  const mutationOptions = getFollowUserMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getUserFollowing = (
  params: GetUserFollowingParams,
  signal?: AbortSignal,
) => {
  return customInstance<PageResponseBasicUserResponse>({
    url: `/user/following`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetUserFollowingQueryKey = (params: GetUserFollowingParams) => {
  return [`/user/following`, ...(params ? [params] : [])] as const;
};

export const getGetUserFollowingInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserFollowing>>,
    GetUserFollowingParams["cursor"]
  >,
  TError = unknown,
>(
  params: GetUserFollowingParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserFollowing>>,
        TError,
        TData,
        Awaited<ReturnType<typeof getUserFollowing>>,
        QueryKey,
        GetUserFollowingParams["cursor"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowingQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowing>>,
    QueryKey,
    GetUserFollowingParams["cursor"]
  > = ({ signal, pageParam }) =>
    getUserFollowing(
      { ...params, cursor: pageParam || params?.["cursor"] },
      signal,
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getUserFollowing>>,
    TError,
    TData,
    Awaited<ReturnType<typeof getUserFollowing>>,
    QueryKey,
    GetUserFollowingParams["cursor"]
  > & { queryKey: QueryKey };
};

export type GetUserFollowingInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowing>>
>;
export type GetUserFollowingInfiniteQueryError = unknown;

export const useGetUserFollowingInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserFollowing>>,
    GetUserFollowingParams["cursor"]
  >,
  TError = unknown,
>(
  params: GetUserFollowingParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserFollowing>>,
        TError,
        TData,
        Awaited<ReturnType<typeof getUserFollowing>>,
        QueryKey,
        GetUserFollowingParams["cursor"]
      >
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetUserFollowingInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetUserFollowingQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserFollowing>>,
  TError = unknown,
>(
  params: GetUserFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowing>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowingQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowing>>
  > = ({ signal }) => getUserFollowing(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserFollowing>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserFollowingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowing>>
>;
export type GetUserFollowingQueryError = unknown;

export const useGetUserFollowing = <
  TData = Awaited<ReturnType<typeof getUserFollowing>>,
  TError = unknown,
>(
  params: GetUserFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowing>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetUserFollowingQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getUserFollowers = (
  params: GetUserFollowersParams,
  signal?: AbortSignal,
) => {
  return customInstance<PageResponseBasicUserResponse>({
    url: `/user/followers`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetUserFollowersQueryKey = (params: GetUserFollowersParams) => {
  return [`/user/followers`, ...(params ? [params] : [])] as const;
};

export const getGetUserFollowersInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserFollowers>>,
    GetUserFollowersParams["cursor"]
  >,
  TError = unknown,
>(
  params: GetUserFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserFollowers>>,
        TError,
        TData,
        Awaited<ReturnType<typeof getUserFollowers>>,
        QueryKey,
        GetUserFollowersParams["cursor"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowers>>,
    QueryKey,
    GetUserFollowersParams["cursor"]
  > = ({ signal, pageParam }) =>
    getUserFollowers(
      { ...params, cursor: pageParam || params?.["cursor"] },
      signal,
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getUserFollowers>>,
    TError,
    TData,
    Awaited<ReturnType<typeof getUserFollowers>>,
    QueryKey,
    GetUserFollowersParams["cursor"]
  > & { queryKey: QueryKey };
};

export type GetUserFollowersInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowers>>
>;
export type GetUserFollowersInfiniteQueryError = unknown;

export const useGetUserFollowersInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserFollowers>>,
    GetUserFollowersParams["cursor"]
  >,
  TError = unknown,
>(
  params: GetUserFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserFollowers>>,
        TError,
        TData,
        Awaited<ReturnType<typeof getUserFollowers>>,
        QueryKey,
        GetUserFollowersParams["cursor"]
      >
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetUserFollowersInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetUserFollowersQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserFollowers>>,
  TError = unknown,
>(
  params: GetUserFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowers>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowers>>
  > = ({ signal }) => getUserFollowers(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserFollowers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserFollowersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowers>>
>;
export type GetUserFollowersQueryError = unknown;

export const useGetUserFollowers = <
  TData = Awaited<ReturnType<typeof getUserFollowers>>,
  TError = unknown,
>(
  params: GetUserFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowers>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetUserFollowersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const searchUsers = (
  params: SearchUsersParams,
  signal?: AbortSignal,
) => {
  return customInstance<PageResponseUserResponse>({
    url: `/open/search`,
    method: "GET",
    params,
    signal,
  });
};

export const getSearchUsersQueryKey = (params: SearchUsersParams) => {
  return [`/open/search`, ...(params ? [params] : [])] as const;
};

export const getSearchUsersInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof searchUsers>>,
    SearchUsersParams["cursor"]
  >,
  TError = unknown,
>(
  params: SearchUsersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof searchUsers>>,
        TError,
        TData,
        Awaited<ReturnType<typeof searchUsers>>,
        QueryKey,
        SearchUsersParams["cursor"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchUsersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchUsers>>,
    QueryKey,
    SearchUsersParams["cursor"]
  > = ({ signal, pageParam }) =>
    searchUsers({ ...params, cursor: pageParam || params?.["cursor"] }, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof searchUsers>>,
    TError,
    TData,
    Awaited<ReturnType<typeof searchUsers>>,
    QueryKey,
    SearchUsersParams["cursor"]
  > & { queryKey: QueryKey };
};

export type SearchUsersInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchUsers>>
>;
export type SearchUsersInfiniteQueryError = unknown;

export const useSearchUsersInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof searchUsers>>,
    SearchUsersParams["cursor"]
  >,
  TError = unknown,
>(
  params: SearchUsersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof searchUsers>>,
        TError,
        TData,
        Awaited<ReturnType<typeof searchUsers>>,
        QueryKey,
        SearchUsersParams["cursor"]
      >
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSearchUsersInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getSearchUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof searchUsers>>,
  TError = unknown,
>(
  params: SearchUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchUsersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchUsers>>> = ({
    signal,
  }) => searchUsers(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchUsers>>
>;
export type SearchUsersQueryError = unknown;

export const useSearchUsers = <
  TData = Awaited<ReturnType<typeof searchUsers>>,
  TError = unknown,
>(
  params: SearchUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSearchUsersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getUserByUsername = (
  username: string,
  params?: GetUserByUsernameParams,
  signal?: AbortSignal,
) => {
  return customInstance<UserResponse>({
    url: `/open/search/${username}`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetUserByUsernameQueryKey = (
  username: string,
  params?: GetUserByUsernameParams,
) => {
  return [`/open/search/${username}`, ...(params ? [params] : [])] as const;
};

export const getGetUserByUsernameInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserByUsername>>,
    GetUserByUsernameParams["cursor"]
  >,
  TError = unknown,
>(
  username: string,
  params?: GetUserByUsernameParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserByUsername>>,
        TError,
        TData,
        Awaited<ReturnType<typeof getUserByUsername>>,
        QueryKey,
        GetUserByUsernameParams["cursor"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserByUsernameQueryKey(username, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserByUsername>>,
    QueryKey,
    GetUserByUsernameParams["cursor"]
  > = ({ signal, pageParam }) =>
    getUserByUsername(
      username,
      { ...params, cursor: pageParam || params?.["cursor"] },
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!username,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getUserByUsername>>,
    TError,
    TData,
    Awaited<ReturnType<typeof getUserByUsername>>,
    QueryKey,
    GetUserByUsernameParams["cursor"]
  > & { queryKey: QueryKey };
};

export type GetUserByUsernameInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserByUsername>>
>;
export type GetUserByUsernameInfiniteQueryError = unknown;

export const useGetUserByUsernameInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserByUsername>>,
    GetUserByUsernameParams["cursor"]
  >,
  TError = unknown,
>(
  username: string,
  params?: GetUserByUsernameParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserByUsername>>,
        TError,
        TData,
        Awaited<ReturnType<typeof getUserByUsername>>,
        QueryKey,
        GetUserByUsernameParams["cursor"]
      >
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetUserByUsernameInfiniteQueryOptions(
    username,
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetUserByUsernameQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserByUsername>>,
  TError = unknown,
>(
  username: string,
  params?: GetUserByUsernameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByUsername>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserByUsernameQueryKey(username, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserByUsername>>
  > = ({ signal }) => getUserByUsername(username, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!username,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserByUsername>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserByUsernameQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserByUsername>>
>;
export type GetUserByUsernameQueryError = unknown;

export const useGetUserByUsername = <
  TData = Awaited<ReturnType<typeof getUserByUsername>>,
  TError = unknown,
>(
  username: string,
  params?: GetUserByUsernameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByUsername>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetUserByUsernameQueryOptions(
    username,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
