/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from "@faker-js/faker";
import { HttpResponse, delay, http } from "msw";

export const getGetUserByUsernameMock = () => ({
  bio: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  email: faker.word.sample(),
  id: faker.string.uuid(),
  image: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  name: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  role: faker.helpers.arrayElement(["USER", "ADMIN"] as const),
  username: faker.word.sample(),
  verified: faker.datatype.boolean(),
});

export const getUserControllerMock = () => [
  http.get("*/user/:username", async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(getGetUserByUsernameMock()), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    });
  }),
];
